import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo } from "next/font/google";
import "./globals.css";
import HeroUiProviderComponent from "@/components/providers/hero-ui-provider";

const CairoFont = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${CairoFont.variable} antialiased`}>
        <HeroUiProviderComponent>{children}</HeroUiProviderComponent>
      </body>
    </html>
  );
}
